In [10]:
import pandas as pd
import numpy as np

In [12]:
path="/content/archive.zip"
df=pd.read_csv(path)

In [17]:
df.head()

   Price  Bedroom   Space  Room   Lot     Tax  Bathroom  Garage  Condition
0   53.0      2.0   967.0   5.0  39.0   652.0       1.5     0.0        0.0
1   55.0      2.0   815.0   5.0  33.0  1000.0       1.0     2.0        1.0
2   56.0      3.0   900.0   5.0  35.0   897.0       1.5     1.0        0.0
3   58.0      3.0  1007.0   6.0  24.0   964.0       1.5     2.0        0.0
4   64.0      3.0  1100.0   7.0  50.0  1099.0       1.5     1.5        0.0

In [53]:
missing_values_count = df.isnull().sum()
display("Missing values count per column:", missing_values_count)

'Missing values count per column:'

Price        0
Bedroom      0
Space        0
Room         0
Lot          0
Tax          0
Bathroom     0
Garage       0
Condition    0
dtype: int64

In [40]:
median_lot=df.Lot.median()
df.Lot.fillna(median_lot, inplace=True)

/tmp/ipython-input-3127712510.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.Lot.fillna(median_lot, inplace=True)

In [24]:
median_betroom=df.Bathroom.median()
median_betroom

1.5

In [26]:
median_bedroom = df.Bedroom.median()
df.Bedroom.fillna(median_bedroom, inplace=True)

/tmp/ipython-input-2434413894.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.Bedroom.fillna(median_bedroom, inplace=True)

In [31]:
median_price=df.Price.median()
df.Price.fillna(median_price, inplace=True)

/tmp/ipython-input-4211929130.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.Price.fillna(median_price, inplace=True)

In [36]:
median_Space=df.Space.median()
df.Space.fillna(median_Space, inplace=True)

/tmp/ipython-input-2161356591.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.Space.fillna(median_Space, inplace=True)

In [38]:
median_room=df.Room.median()
df.Room.fillna(median_room, inplace=True)

/tmp/ipython-input-394464424.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.Room.fillna(median_room, inplace=True)

In [44]:
median_batroom=df.Bathroom.median()
df.Bathroom.fillna(median_batroom, inplace=True)

In [45]:
median_tax=df.Tax.median()
df.Tax.fillna(median_tax, inplace=True)

/tmp/ipython-input-2446767994.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.Tax.fillna(median_tax, inplace=True)

In [50]:
median_condition=df.Condition.median()

df.Condition.fillna(median_condition, inplace=True)

/tmp/ipython-input-816142871.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.Condition.fillna(median_condition, inplace=True)

In [52]:
median_Garage=df.Garage.median()
df.Garage.fillna(median_Garage, inplace=True)

In [55]:
import matplotlib.pyplot as plt

In [68]:
from sklearn import linear_model
reg=linear_model.LinearRegression()
reg.fit(df[['Bedroom','Space','Room','Lot','Tax','Bathroom','Garage','Condition']],df.Price)

LinearRegression()

In [67]:
reg.predict([[2.0,967.0,5.0,39.0,652.0,1.5,0.0,	0.0]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([50.94132748])